### ISSUE TITLE
Pylint 2.0.1 AttributeError: module 'concurrent.futures' has no attribute '_base' at...

### ISSUE THREAD

**Issue by xNinjaKittyx** [AtomLinter/linter-pylint#214]
I've been getting this error ever since updating. 
```
AttributeError: module 'concurrent.futures' has no attribute '_base'
    at Object.<anonymous> (file:///C:/Users/X/.atom/packages/linter-pylint/lib/main.js:159:17)
    at next (<anonymous>)
    at step (C:\Users\X\.atom\packages\linter-pylint\lib\main.js:5:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The whole error is here: https://pastebin.com/216cs6aZ

**Comment by ddaanet** [comment]
Here is probably the source of your problem:
```
  File "c:\program files\python35\lib\tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "C:\Users\Dan\Documents\GitHub\KoyomiBot\modules\random.py", line 3, in <module>
    import asyncio
```
Which is caused by #104 .

@xNinjaKittyx does this change fix your problem?
https://github.com/AtomLinter/linter-pylint/pull/213/files

@Arcanemagus can we have a release with the fix for #104 ?

**Comment by xNinjaKittyx** [comment]
@ddaanet I can confirm that this fixes my problem.
Thank you

**Comment by ddaanet** [comment]
Duplicate of #104
